import {FC} from 'react';
import Head from 'next/head'
import styles from './Home.module.scss'
import OurCars from '@/components/ui/ourcars/OurCars';
import HookForm from '@/components/ui/form/Form';
import Layout from '@/components/layout/Layout';
import Features from '@/components/ui/features/Features';
import {ICarData} from '@/interfaces/car.interface';
 
const Home: FC<ICarData> = () => {
    return (
        <Layout title='Home' description='SEO stands for Search Engine Optimization'>
            <Head>
                <title>Next.js</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
            <h1 className={styles.motto}>Experience luxury on the road with our premium car rentals <br /> Rent your dream car and make your journey unforgettable.</h1> 
            </header>
            <div className="container">
                <main className={styles.main}>
                    <h3 className={styles.description}>Welcome to our premium car rental website where you can find a wide selection of luxurious vehicles to make your next journey unforgettable. From sleek and powerful sports cars like BMW, Mercedes, Bentley, Porshe, Mclaren, and Ferrari to elegant and sophisticated sedans like Audi and Cadillac, we have the perfect ride for any occasion. Whether you're looking to impress on a special date night, enjoy a weekend getaway in style, or simply want to indulge in the joy of driving, our diverse fleet of high-end cars will take you there. Experience the ultimate in comfort, performance, and style by renting one of our exclusive cars today.</h3>
                    <Features />
                    <OurCars />
                    <HookForm />
                </main>
            </div>
        </Layout>
    );
}

export default Home;